### ISSUE TITLE
Install pyCapsid in UM HPC

### ISSUE THREAD

**Issue by luque82** [luquelab/pyCapsid#82]
+ Install pyCapsid in the UM HPC (IDSC).
+ Try Pegasus and Triton.
+ Identify difficulties during the installation.
+ Coordinate with the IDSC team to address issues.
+ Document the process.

**Comment by abelardoacm** [comment]
### Update
- [x] Pycasid installed + tested in UM HPC ***Pegasus***
- [x] - it could not be installed in UM HPC ***Triton***

### Details

- Triton's architecture is a **linux-ppc64le"** for which some dependencies either generate conflicts (numba, numpy, scipy, scikit-learn, statsmodels) or are missing (biotite). Conflictive dependencies could be solved by specifying the versions within a conda environment, but **biotite** issue could not be solved. Biotite has no ppc64le version pre-built but it also could not be compiled from source as it needs GCC >= 8.4, not available in Triton. As per suggested in **biotite's** documentation, a [specific conda env](http://raw.githubusercontent.com/biotite-dev/biotite/master/environment.yml) can be used to compile, unfortunately this strategy fails as the environment itself is not solvable within Triton's architecture.
- The dependencies could be compiled manually, however this generates a very unfavorable tradeoff for the maintenance and compatibility of the installation, since manual compilation at various levels would be required.

### WIP

- [x] Writing documentation for the installation steps followed in UM HPC Pegasus

**Comment by abelardoacm** [comment]
Done :
- [x] Install pyCapsid in the UM HPC (IDSC).
- [x] Try Pegasus and Triton.
- [x] Identify difficulties during the installation.
- [x] Coordinate with the IDSC team to address issues.
- [x] Document the process.

NOTES: pyCapsid is installed and properly executed in UM HPC, within the conda environment **pycapsid** (env path: */nethome/axa3896/anaconda3/envs/pycapsid*). Documentation on the suggested HPC install procedure can be found [here](https://luquelab.github.io/pyCapsid/installation/), as well as a [YAML file](https://github.com/luquelab/pyCapsid/blob/main/docs/installation/pycapsid_environment.yml) to reproduce UM Pegasus installation.
